httpProxy: "http://127.0.0.1:5000"

httpsProxy: "http://127.0.0.1:5000"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs

nodeLinker: node-modules
